__4.7 Deriving New Variables __

In [2]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [5]:
#importing order_product_merged.pki
df_orders_products_merged = pd.read_pickle(r'/Users/rayruslijunior/11-2021 Instacart Basket Analysis/02 Data/Prepared Data/orders_products_merged.pkl')

In [7]:
#limiting our dataframe to only 1.000.000
df= df_orders_products_merged[:1000000]

__Using If command__

In [8]:
#setting and definition for price_label collumn with an If condition
def price_label(row):

  if row['prices'] <= 5:
    return 'Low-range product'
  elif (row['prices'] > 5) and (row['prices'] <= 15):
    return 'Mid-range product'
  elif row['prices'] > 15:
    return 'High range'
  else: return 'Not enough data'

In [9]:
df['price_range'] = df.apply(price_label, axis=1)

<ipython-input-9-fe64de1169c8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price_range'] = df.apply(price_label, axis=1)

In [11]:
df.shape

(1000000, 16)

In [12]:
df['price_range'].value_counts(dropna = False)

Mid-range product    668114
Low-range product    312168
High range            12340
Not enough data        7378
Name: price_range, dtype: int64

In [13]:
df['prices'].max()

99999.0

__Using Loc Command__

In [18]:
df.loc[df['prices'] > 15, 'price_range_loc'] = 'High-range product'

/Users/rayruslijunior/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [16]:
df.loc[(df['prices'] <= 15) & (df['prices'] > 5), 'price_range_loc'] = 'Mid-range product'

/Users/rayruslijunior/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [17]:
df.loc[df['prices'] <= 5, 'price_range_loc'] = 'Low-range product'

/Users/rayruslijunior/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [19]:
df['price_range_loc'].value_counts(dropna = False)

Mid-range product     668114
Low-range product     312168
High-range product     12340
NaN                     7378
Name: price_range_loc, dtype: int64

__Let's use the entire data set now!__

In [21]:
ords_prods_merged = pd.read_pickle(r'/Users/rayruslijunior/11-2021 Instacart Basket Analysis/02 Data/Prepared Data/orders_products_merged.pkl')

In [25]:
ords_prods_merged.shape

(32641268, 15)

In [26]:
ords_prods_merged.loc[ords_prods_merged['prices'] > 15,'price_range_loc'] = 'High-range product'

In [30]:
ords_prods_merged.loc[(ords_prods_merged['prices'] <=15) & (ords_prods_merged['prices']>5),'price_range_loc'] = 'Mid-range product'

In [31]:
ords_prods_merged.loc[ords_prods_merged['prices'] <= 5,'price_range_loc'] = 'Low-range product'

In [32]:
ords_prods_merged['price_range_loc'].value_counts(dropna = False)

Mid-range product     21860860
Low-range product     10126321
High-range product      417678
NaN                     236409
Name: price_range_loc, dtype: int64

__If Statement with For Loops__

In [33]:
print("my age is 30")

my age is 30

In [34]:
print("my age is 31")

my age is 31

In [35]:
for x in range (30,45):
    print("my age is %d" %(x))

my age is 30
my age is 31
my age is 32
my age is 33
my age is 34
my age is 35
my age is 36
my age is 37
my age is 38
my age is 39
my age is 40
my age is 41
my age is 42
my age is 43
my age is 44

__Back to the ords_prods_merged__

In [37]:
ords_prods_merged.head(10)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Mid-range product
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product
5,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product
6,2398795,1,2,3,7,15.0,False,10258.0,2.0,0.0,Pistachios,117.0,19.0,3.0,both,Low-range product
7,2398795,1,2,3,7,15.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product
8,2398795,1,2,3,7,15.0,False,13176.0,4.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product
9,2398795,1,2,3,7,15.0,False,26088.0,5.0,1.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product

In [38]:
ords_prods_merged['order_dow'].value_counts(dropna = False)

0    6252941
1    5696724
6    4530304
2    4243173
5    4236989
3    3868747
4    3812390
Name: order_dow, dtype: int64

In [40]:
result = []

for value in ords_prods_merged["order_dow"]:
  if value == 0:
    result.append("Busiest day")
  elif value == 4:
    result.append("Least busy")
  else:
    result.append("Regularly busy")

In [41]:
result

['Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Least busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Busiest day',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 'Regularly busy',
 ...]

In [42]:
ords_prods_merged['busiest_day'] = result

In [43]:
ords_prods_merged['busiest_day'].value_counts(dropna = False)

Regularly busy    22575937
Busiest day        6252941
Least busy         3812390
Name: busiest_day, dtype: int64

__TASK 4.7__ (i got this!!!)

In [44]:
#1. price_label and busiest_day are on the table
ords_prods_merged.head(5)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy

In [46]:
#2.Suppose your clients have changed their minds about the labels you created in your “busiest_day” column. Now, they want “Busiest day” to become “Busiest days” (plural). This label should correspond with the two busiest days of the week as opposed to the single busiest day. At the same time, they’d also like to know the two slowest days. Create a new column for this using a suitable method.
ords_prods_merged['order_dow'].value_counts(dropna = False)

0    6252941
1    5696724
6    4530304
2    4243173
5    4236989
3    3868747
4    3812390
Name: order_dow, dtype: int64

In [59]:
result = []

for value in ords_prods_merged["order_dow"]:
  if value == 0 or value == 1:
    result.append("Busiest days")
  elif value == 4 or value == 3:
    result.append("slowest days")
  else:
    result.append("Regularly busy days")

In [60]:
ords_prods_merged['busiest_days'] = result

In [63]:
#3. check the accuracy 
ords_prods_merged['busiest_days'].value_counts(dropna = False)

Regularly busy days    13010466
Busiest days           11949665
slowest days            7681137
Name: busiest_days, dtype: int64

In [64]:
#observation: the new collumn calculation in correct, busiest day is a combination of 0 & 1; regularly busy days is a total of 6,2 & 5 and the slowest days is the total of 3 & 4

In [65]:
ords_prods_merged.head(30)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy days
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy days
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy days
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy days
5,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days
6,2398795,1,2,3,7,15.0,False,10258.0,2.0,0.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days
7,2398795,1,2,3,7,15.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days
8,2398795,1,2,3,7,15.0,False,13176.0,4.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,slowest days
9,2398795,1,2,3,7,15.0,False,26088.0,5.0,1.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,slowest days
10,2398795,1,2,3,7,15.0,False,13032.0,6.0,0.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,slowest days
11,473747,1,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days
12,473747,1,3,3,12,21.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days
13,473747,1,3,3,12,21.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days
14,473747,1,3,3,12,21.0,False,25133.0,4.0,0.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,slowest days
15,473747,1,3,3,12,21.0,False,30450.0,5.0,0.0,Creamy Almond Butter,88.0,13.0,3.2,both,Low-range product,Regularly busy,slowest days
16,2254736,1,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days
17,2254736,1,4,4,7,29.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days
18,2254736,1,4,4,7,29.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days
19,2254736,1,4,4,7,29.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days
20,2254736,1,4,4,7,29.0,False,26405.0,5.0,1.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Least busy,slowest days
21,431534,1,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days
22,431534,1,5,4,15,28.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days
23,431534,1,5,4,15,28.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days
24,431534,1,5,4,15,28.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days
25,431534,1,5,4,15,28.0,False,10326.0,5.0,0.0,Organic Fuji Apples,24.0,4.0,2.7,both,Low-range product,Least busy,slowest days
26,431534,1,5,4,15,28.0,False,17122.0,6.0,0.0,Honeycrisp Apples,24.0,4.0,14.0,both,Mid-range product,Least busy,slowest days
27,431534,1,5,4,15,28.0,False,41787.0,7.0,0.0,Bartlett Pears,24.0,4.0,5.0,both,Low-range product,Least busy,slowest days
28,431534,1,5,4,15,28.0,False,13176.0,8.0,1.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Least busy,slowest days
29,3367565,1,6,2,7,19.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days

#4.When too many users make Instacart orders at the same time, the app freezes. The senior technical officer at Instacart wants you to identify the busiest hours of the day. Rather than by hour, they want periods of time labeled “Most orders,” “Average orders,” and “Fewest orders.” Create a new column containing these labels called “busiest_period_of_day.”

In [66]:
#first let's check the list of hour when order is submitted
ords_prods_merged['order_hour_of_day'].value_counts(dropna = False)

10    2781009
11    2755369
14    2709084
15    2682090
13    2680171
12    2637533
16    2554110
9     2471067
17    2104225
8     1729871
18    1649870
19    1268365
20     983232
7      897163
21     801052
22     638671
23     405051
6      292533
0      220337
1      116589
5       88661
2       69904
4       53636
3       51675
Name: order_hour_of_day, dtype: int64

In [67]:
ords_prods_merged.shape

(32641268, 18)

In [78]:
result = []

for value in ords_prods_merged["order_hour_of_day"]:
  if value >= 9 and value <= 16:
    result.append("Most orders")
  elif value <= 6 or value == 23:
    result.append("Fewest orders")
  else:
    result.append("Average orders")

In [79]:
ords_prods_merged['busiest_period_of_day'] = result

In [80]:
#7.check % printing the accuracy
ords_prods_merged['busiest_period_of_day'].value_counts(dropna = False)

Most orders       21270433
Average orders    10072449
Fewest orders      1298386
Name: busiest_period_of_day, dtype: int64

In [82]:
ords_prods_merged.head(30)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,order_time_loc,busiest_period_of_day
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days,NaN,Average orders
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy days,NaN,Average orders
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy days,NaN,Average orders
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy days,NaN,Average orders
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy days,NaN,Average orders
5,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,NaN,Average orders
6,2398795,1,2,3,7,15.0,False,10258.0,2.0,0.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,NaN,Average orders
7,2398795,1,2,3,7,15.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,NaN,Average orders
8,2398795,1,2,3,7,15.0,False,13176.0,4.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,slowest days,NaN,Average orders
9,2398795,1,2,3,7,15.0,False,26088.0,5.0,1.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,slowest days,NaN,Average orders
10,2398795,1,2,3,7,15.0,False,13032.0,6.0,0.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,slowest days,NaN,Average orders
11,473747,1,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Most Orders,Most orders
12,473747,1,3,3,12,21.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Most Orders,Most orders
13,473747,1,3,3,12,21.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Most Orders,Most orders
14,473747,1,3,3,12,21.0,False,25133.0,4.0,0.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,slowest days,Most Orders,Most orders
15,473747,1,3,3,12,21.0,False,30450.0,5.0,0.0,Creamy Almond Butter,88.0,13.0,3.2,both,Low-range product,Regularly busy,slowest days,Most Orders,Most orders
16,2254736,1,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,NaN,Average orders
17,2254736,1,4,4,7,29.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,NaN,Average orders
18,2254736,1,4,4,7,29.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,NaN,Average orders
19,2254736,1,4,4,7,29.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,NaN,Average orders
20,2254736,1,4,4,7,29.0,False,26405.0,5.0,1.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Least busy,slowest days,NaN,Average orders
21,431534,1,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,Most Orders,Most orders
22,431534,1,5,4,15,28.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,Most Orders,Most orders
23,431534,1,5,4,15,28.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,Most Orders,Most orders
24,431534,1,5,4,15,28.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,Most Orders,Most orders
25,431534,1,5,4,15,28.0,False,10326.0,5.0,0.0,Organic Fuji Apples,24.0,4.0,2.7,both,Low-range product,Least busy,slowest days,Most Orders,Most orders
26,431534,1,5,4,15,28.0,False,17122.0,6.0,0.0,Honeycrisp Apples,24.0,4.0,14.0,both,Mid-range product,Least busy,slowest days,Most Orders,Most orders
27,431534,1,5,4,15,28.0,False,41787.0,7.0,0.0,Bartlett Pears,24.0,4.0,5.0,both,Low-range product,Least busy,slowest days,Most Orders,Most orders
28,431534,1,5,4,15,28.0,False,13176.0,8.0,1.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Least busy,slowest days,Most Orders,Most orders
29,3367565,1,6,2,7,19.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days,NaN,Average orders

In [83]:
#needed to delete the order_time_loc :-) failed attempt
ords_prods_merged.drop('order_time_loc',axis=1,inplace=True)

In [84]:
ords_prods_merged.head()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy days,Average orders
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders

In [86]:
#exporting data frame as pickle size 
ords_prods_merged.to_pickle(r'/Users/rayruslijunior/11-2021 Instacart Basket Analysis/02 Data/Prepared Data/orders_products_merged_addition.pkl')