__Grouping Data__

In [3]:
# Import libraries
import pandas as pd
import numpy as np
import os

In [4]:
#importing order_product_merged.pki from task 4.7
ords_prods_merge = pd.read_pickle(r'/Users/rayruslijunior/11-2021 Instacart Basket Analysis/02 Data/Prepared Data/orders_products_merged_addition.pkl')

In [5]:
#creating a subset 
df = ords_prods_merge[:1000000]

In [6]:
#let's check the shape of our new df
df.shape

(1000000, 19)

In [7]:
df.head(10)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy days,Average orders
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders
5,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Average orders
6,2398795,1,2,3,7,15.0,False,10258.0,2.0,0.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Average orders
7,2398795,1,2,3,7,15.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Average orders
8,2398795,1,2,3,7,15.0,False,13176.0,4.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,slowest days,Average orders
9,2398795,1,2,3,7,15.0,False,26088.0,5.0,1.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,slowest days,Average orders

In [8]:
#implemented groupby function
df.groupby('product_name')

In [9]:
#splitting the data based on 'department_id'
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              14.794925
2.0              17.085793
3.0              17.892742
4.0              17.880137
5.0              15.108513
6.0              15.352869
7.0              17.682741
8.0              16.496386
9.0              15.944846
10.0             20.104831
11.0             16.483104
12.0             15.614125
13.0             16.458631
14.0             17.523399
15.0             15.673392
16.0             18.012021
17.0             15.842139
18.0             19.349156
19.0             17.625805
20.0             17.113240
21.0             22.009038

In [10]:
#adding additional collumn 'mean' on the department_id
df.groupby('department_id')['order_number'].mean()

department_id
1.0     14.794925
2.0     17.085793
3.0     17.892742
4.0     17.880137
5.0     15.108513
6.0     15.352869
7.0     17.682741
8.0     16.496386
9.0     15.944846
10.0    20.104831
11.0    16.483104
12.0    15.614125
13.0    16.458631
14.0    17.523399
15.0    15.673392
16.0    18.012021
17.0    15.842139
18.0    19.349156
19.0    17.625805
20.0    17.113240
21.0    22.009038
Name: order_number, dtype: float64

In [11]:
df.groupby('department_id').order_number.mean()

department_id
1.0     14.794925
2.0     17.085793
3.0     17.892742
4.0     17.880137
5.0     15.108513
6.0     15.352869
7.0     17.682741
8.0     16.496386
9.0     15.944846
10.0    20.104831
11.0    16.483104
12.0    15.614125
13.0    16.458631
14.0    17.523399
15.0    15.673392
16.0    18.012021
17.0    15.842139
18.0    19.349156
19.0    17.625805
20.0    17.113240
21.0    22.009038
Name: order_number, dtype: float64

In [10]:
#performing mutiple aggregation
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1.0              14.794925   1  99
2.0              17.085793   1  98
3.0              17.892742   1  99
4.0              17.880137   1  99
5.0              15.108513   1  99
6.0              15.352869   1  99
7.0              17.682741   1  99
8.0              16.496386   1  91
9.0              15.944846   1  99
10.0             20.104831   1  99
11.0             16.483104   1  99
12.0             15.614125   1  99
13.0             16.458631   1  99
14.0             17.523399   1  99
15.0             15.673392   1  99
16.0             18.012021   1  99
17.0             15.842139   1  99
18.0             19.349156   1  99
19.0             17.625805   1  99
20.0             17.113240   1  99
21.0             22.009038   1  97

__Aggregrating Data with transform()__

In [12]:
#applying max_order
ords_prods_merge['max_order'] = ords_prods_merge.groupby(['user_id'])['order_number'].transform(np.max)

In [13]:
#checking if our command has been applied with the first 100 row
ords_prods_merge.head(100)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,11
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,11
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,738281,2,4,2,10,8.0,False,9681.0,12.0,0.0,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
96,738281,2,4,2,10,8.0,False,21150.0,13.0,0.0,Fire Grilled Steak Bowl,38.0,1.0,5.9,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
97,1673511,2,5,3,11,8.0,False,47144.0,1.0,0.0,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,both,Mid-range product,Regularly busy,slowest days,Most orders,15
98,1673511,2,5,3,11,8.0,False,5322.0,2.0,0.0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,both,Low-range product,Regularly busy,slowest days,Most orders,15
99,1673511,2,5,3,11,8.0,False,17224.0,3.0,0.0,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,both,Low-range product,Regularly busy,slowest days,Most orders,15

In [14]:
#command to display all the row
pd.options.display.max_rows = None

In [15]:
ords_prods_merge.head(100)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,11
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,Organic Unsweetened Vanilla Almond Milk,91.0,16.0,12.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,11
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11
5,2398795,1,2,3,7,15.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Average orders,11
6,2398795,1,2,3,7,15.0,False,10258.0,2.0,0.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Average orders,11
7,2398795,1,2,3,7,15.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Average orders,11
8,2398795,1,2,3,7,15.0,False,13176.0,4.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,slowest days,Average orders,11
9,2398795,1,2,3,7,15.0,False,26088.0,5.0,1.0,Aged White Cheddar Popcorn,23.0,19.0,4.7,both,Low-range product,Regularly busy,slowest days,Average orders,11
10,2398795,1,2,3,7,15.0,False,13032.0,6.0,0.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,slowest days,Average orders,11
11,473747,1,3,3,12,21.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,slowest days,Most orders,11
12,473747,1,3,3,12,21.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,slowest days,Most orders,11
13,473747,1,3,3,12,21.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,slowest days,Most orders,11
14,473747,1,3,3,12,21.0,False,25133.0,4.0,0.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,slowest days,Most orders,11
15,473747,1,3,3,12,21.0,False,30450.0,5.0,0.0,Creamy Almond Butter,88.0,13.0,3.2,both,Low-range product,Regularly busy,slowest days,Most orders,11
16,2254736,1,4,4,7,29.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,Average orders,11
17,2254736,1,4,4,7,29.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,Average orders,11
18,2254736,1,4,4,7,29.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,Average orders,11
19,2254736,1,4,4,7,29.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,Average orders,11
20,2254736,1,4,4,7,29.0,False,26405.0,5.0,1.0,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,both,Low-range product,Least busy,slowest days,Average orders,11
21,431534,1,5,4,15,28.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,Most orders,11
22,431534,1,5,4,15,28.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,Most orders,11
23,431534,1,5,4,15,28.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,Most orders,11
24,431534,1,5,4,15,28.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,Most orders,11
25,431534,1,5,4,15,28.0,False,10326.0,5.0,0.0,Organic Fuji Apples,24.0,4.0,2.7,both,Low-range product,Least busy,slowest days,Most orders,11
26,431534,1,5,4,15,28.0,False,17122.0,6.0,0.0,Honeycrisp Apples,24.0,4.0,14.0,both,Mid-range product,Least busy,slowest days,Most orders,11
27,431534,1,5,4,15,28.0,False,41787.0,7.0,0.0,Bartlett Pears,24.0,4.0,5.0,both,Low-range product,Least busy,slowest days,Most orders,11
28,431534,1,5,4,15,28.0,False,13176.0,8.0,1.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Least busy,slowest days,Most orders,11
29,3367565,1,6,2,7,19.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,11
30,3367565,1,6,2,7,19.0,False,12427.0,2.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11
31,3367565,1,6,2,7,19.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11
32,3367565,1,6,2,7,19.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,11
33,550135,1,7,1,9,20.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,11
34,550135,1,7,1,9,20.0,False,10258.0,2.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,11
35,550135,1,7,1,9,20.0,False,12427.0,3.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,11
36,550135,1,7,1,9,20.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,11
37,550135,1,7,1,9,20.0,False,13032.0,5.0,1.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Regularly busy,Busiest days,Most orders,11
38,3108588,1,8,1,14,14.0,False,12427.0,1.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,11
39,3108588,1,8,1,14,14.0,False,196.0,2.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,11
40,3108588,1,8,1,14,14.0,False,10258.0,3.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,11
41,3108588,1,8,1,14,14.0,False,25133.0,4.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,11
42,3108588,1,8,1,14,14.0,False,46149.0,5.0,0.0,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Regularly busy,Busiest days,Most orders,11
43,3108588,1,8,1,14,14.0,False,49235.0,6.0,0.0,Organic Half & Half,53.0,16.0,1.8,both,Low-range product,Regularly busy,Busiest days,Most orders,11
44,2295261,1,9,1,16,0.0,False,49235.0,1.0,1.0,Organic Half & Half,53.0,16.0,1.8,both,Low-range product,Regularly busy,Busiest days,Most orders,11
45,2295261,1,9,1,16,0.0,False,46149.0,2.0,1.0,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Regularly busy,Busiest days,Most orders,11
46,2295261,1,9,1,16,0.0,False,25133.0,3.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,11
47,2295261,1,9,1,16,0.0,False,196.0,4.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Regularly busy,Busiest days,Most orders,11
48,2295261,1,9,1,16,0.0,False,10258.0,5.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Regularly busy,Busiest days,Most orders,11
49,2295261,1,9,1,16,0.0,False,12427.0,6.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Regularly busy,Busiest days,Most orders,11
50,2550362,1,10,4,8,30.0,False,196.0,1.0,1.0,Soda,77.0,7.0,9.0,both,Mid-range product,Least busy,slowest days,Average orders,11
51,2550362,1,10,4,8,30.0,False,46149.0,2.0,1.0,Zero Calorie Cola,77.0,7.0,13.4,both,Mid-range product,Least busy,slowest days,Average orders,11
52,2550362,1,10,4,8,30.0,False,39657.0,3.0,0.0,Milk Chocolate Almonds,45.0,19.0,6.8,both,Mid-range product,Least busy,slowest days,Average orders,11
53,2550362,1,10,4,8,30.0,False,38928.0,4.0,0.0,0% Greek Strained Yogurt,120.0,16.0,12.6,both,Mid-range product,Least busy,slowest days,Average orders,11
54,2550362,1,10,4,8,30.0,False,25133.0,5.0,1.0,Organic String Cheese,21.0,16.0,8.6,both,Mid-range product,Least busy,slowest days,Average orders,11
55,2550362,1,10,4,8,30.0,False,10258.0,6.0,1.0,Pistachios,117.0,19.0,3.0,both,Low-range product,Least busy,slowest days,Average orders,11
56,2550362,1,10,4,8,30.0,False,35951.0,7.0,0.0,Organic Unsweetened Almond Milk,91.0,16.0,1.3,both,Low-range product,Least busy,slowest days,Average orders,11
57,2550362,1,10,4,8,30.0,False,13032.0,8.0,1.0,Cinnamon Toast Crunch,121.0,14.0,4.0,both,Low-range product,Least busy,slowest days,Average orders,11
58,2550362,1,10,4,8,30.0,False,12427.0,9.0,1.0,Original Beef Jerky,23.0,19.0,4.4,both,Low-range product,Least busy,slowest days,Average orders,11
59,1187899,1,11,4,8,14.0,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,NaN,Least busy,slowest days,Average orders,11
60,2168274,2,1,2,11,NaN,True,32792.0,1.0,0.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
61,2168274,2,1,2,11,NaN,True,47766.0,2.0,0.0,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
62,2168274,2,1,2,11,NaN,True,20574.0,3.0,0.0,Roasted Turkey,96.0,20.0,2.3,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
63,2168274,2,1,2,11,NaN,True,12000.0,4.0,0.0,Baked Organic Sea Salt Crunchy Pea Snack,72.0,13.0,10.9,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
64,2168274,2,1,2,11,NaN,True,48110.0,5.0,0.0,Thin Stackers Brown Rice Lightly Salted,78.0,19.0,2.7,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
65,2168274,2,1,2,11,NaN,True,22474.0,6.0,0.0,Cheddar Bunnies Snack Crackers,78.0,19.0,4.1,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
66,2168274,2,1,2,11,NaN,True,16589.0,7.0,0.0,Plantain Chips,107.0,19.0,5.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
67,2168274,2,1,2,11,NaN,True,35917.0,8.0,0.0,Organic Just Concord Grape Juice,98.0,7.0,9.4,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
68,2168274,2,1,2,11,NaN,True,27344.0,9.0,0.0,Uncured Genoa Salami,96.0,20.0,14.8,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
69,2168274,2,1,2,11,NaN,True,30489.0,10.0,0.0,Original Hummus,67.0,20.0,7.5,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
70,2168274,2,1,2,11,NaN,True,27966.0,11.0,0.0,Organic Raspberries,123.0,4.0,4.4,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
71,2168274,2,1,2,11,NaN,True,13176.0,12.0,0.0,Bag of Organic Bananas,24.0,4.0,10.3,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
72,2168274,2,1,2,11,NaN,True,45066.0,13.0,0.0,Honeycrisp Apple,24.0,4.0,2.5,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
73,1501582,2,2,5,10,10.0,False,16797.0,1.0,0.0,Strawberries,24.0,4.0,1.3,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
74,1501582,2,2,5,10,10.0,False,47526.0,2.0,0.0,Goat Cheese Log,21.0,16.0,2.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
75,1501582,2,2,5,10,10.0,False,8479.0,3.0,0.0,Original Black Box Tablewater Cracker,78.0,19.0,3.5,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
76,1501582,2,2,5,10,10.0,False,47766.0,4.0,1.0,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
77,1501582,2,2,5,10,10.0,False,19051.0,5.0,0.0,"Pita Chips, Simply Naked, Party Size",107.0,19.0,3.9,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
78,1501582,2,2,5,10,10.0,False,8138.0,6.0,0.0,Traditional Hummus,67.0,20.0,2.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
79,1901567,2,3,1,10,3.0,False,47766.0,1.0,1.0,Organic Avocado,24.0,4.0,6.3,both,Mid-range product,Regularly busy,Busiest days,Most orders,15
80,1901567,2,3,1,10,3.0,False,32792.0,2.0,1.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,Busiest days,Most orders,15
81,1901567,2,3,1,10,3.0,False,20574.0,3.0,1.0,Roasted Turkey,96.0,20.0,2.3,both,Low-range product,Regularly busy,Busiest days,Most orders,15
82,1901567,2,3,1,10,3.0,False,7781.0,4.0,0.0,Organic Sticks Low Moisture Part Skim Mozzarel...,21.0,16.0,6.6,both,Mid-range product,Regularly busy,Busiest days,Most orders,15
83,1901567,2,3,1,10,3.0,False,28874.0,5.0,0.0,Carrot Ginger Soup,1.0,20.0,6.2,both,Mid-range product,Regularly busy,Busiest days,Most orders,15
84,738281,2,4,2,10,8.0,False,49451.0,1.0,0.0,Artichoke Spinach Dip,67.0,20.0,7.1,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
85,738281,2,4,2,10,8.0,False,32792.0,2.0,1.0,Chipotle Beef & Pork Realstick,23.0,19.0,5.2,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
86,738281,2,4,2,10,8.0,False,32139.0,3.0,0.0,Hommus Classic Original,67.0,20.0,7.5,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
87,738281,2,4,2,10,8.0,False,34688.0,4.0,0.0,Good Belly Probiotics Juice Drink Blueberry Ac...,31.0,7.0,5.8,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
88,738281,2,4,2,10,8.0,False,36735.0,5.0,0.0,Organic Roasted Sliced Chicken Breast,96.0,20.0,8.9,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
89,738281,2,4,2,10,8.0,False,37646.0,6.0,0.0,Organic Gala Apples,24.0,4.0,9.1,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
90,738281,2,4,2,10,8.0,False,22829.0,7.0,0.0,Multigrain Flax Seeded Flatbread Crackers,78.0,19.0,5.5,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
91,738281,2,4,2,10,8.0,False,24852.0,8.0,0.0,Banana,24.0,4.0,12.3,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
92,738281,2,4,2,10,8.0,False,47209.0,9.0,0.0,Organic Hass Avocado,24.0,4.0,4.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
93,738281,2,4,2,10,8.0,False,33276.0,10.0,0.0,Kalamata Olive Spread,67.0,20.0,10.8,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
94,738281,2,4,2,10,8.0,False,45613.0,11.0,0.0,Pad Thai,38.0,1.0,12.6,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
95,738281,2,4,2,10,8.0,False,9681.0,12.0,0.0,Chicken Tikka Masala with Cumin Infused Basmat...,38.0,1.0,2.0,both,Low-range product,Regularly busy,Regularly busy days,Most orders,15
96,738281,2,4,2,10,8.0,False,21150.0,13.0,0.0,Fire Grilled Steak Bowl,38.0,1.0,5.9,both,Mid-range product,Regularly busy,Regularly busy days,Most orders,15
97,1673511,2,5,3,11,8.0,False,47144.0,1.0,0.0,Unsweetened Original Almond Breeze Almond Milk,91.0,16.0,14.0,both,Mid-range product,Regularly busy,slowest days,Most orders,15
98,1673511,2,5,3,11,8.0,False,5322.0,2.0,0.0,Gluten Free Dark Chocolate Chunk Chewy with a ...,3.0,19.0,2.9,both,Low-range product,Regularly busy,slowest days,Most orders,15
99,1673511,2,5,3,11,8.0,False,17224.0,3.0,0.0,Oats & Honey Gluten Free Granola,3.0,19.0,1.6,both,Low-range product,Regularly busy,slowest days,Most orders,15

__Deriving Columns with loc()__

In [16]:
#we are now trying to create a flag on our customers - based on their number of order
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [17]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [18]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [19]:
#checking the consistency of our flagged
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    16381472
Loyal customer      10679578
New customer         5580218
Name: loyalty_flag, dtype: int64

In [20]:
#setting a condition for our 'loyalty_flag' collumn
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [21]:
#checking the consistency on our whole data set
ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

Regular customer    16381472
Loyal customer      10679578
New customer         5580218
Name: loyalty_flag, dtype: int64

In [22]:
ords_prods_merge.shape

(32641268, 21)

In [23]:
#to see if our new collumn has been implemented correctly on our data set
ords_prods_merge[['user_id','loyalty_flag','order_number']].head(100)

    user_id      loyalty_flag  order_number
0         1  Regular customer             1
1         1  Regular customer             1
2         1  Regular customer             1
3         1  Regular customer             1
4         1  Regular customer             1
5         1  Regular customer             2
6         1  Regular customer             2
7         1  Regular customer             2
8         1  Regular customer             2
9         1  Regular customer             2
10        1  Regular customer             2
11        1  Regular customer             3
12        1  Regular customer             3
13        1  Regular customer             3
14        1  Regular customer             3
15        1  Regular customer             3
16        1  Regular customer             4
17        1  Regular customer             4
18        1  Regular customer             4
19        1  Regular customer             4
20        1  Regular customer             4
21        1  Regular customer             5
22        1  Regular customer             5
23        1  Regular customer             5
24        1  Regular customer             5
25        1  Regular customer             5
26        1  Regular customer             5
27        1  Regular customer             5
28        1  Regular customer             5
29        1  Regular customer             6
30        1  Regular customer             6
31        1  Regular customer             6
32        1  Regular customer             6
33        1  Regular customer             7
34        1  Regular customer             7
35        1  Regular customer             7
36        1  Regular customer             7
37        1  Regular customer             7
38        1  Regular customer             8
39        1  Regular customer             8
40        1  Regular customer             8
41        1  Regular customer             8
42        1  Regular customer             8
43        1  Regular customer             8
44        1  Regular customer             9
45        1  Regular customer             9
46        1  Regular customer             9
47        1  Regular customer             9
48        1  Regular customer             9
49        1  Regular customer             9
50        1  Regular customer            10
51        1  Regular customer            10
52        1  Regular customer            10
53        1  Regular customer            10
54        1  Regular customer            10
55        1  Regular customer            10
56        1  Regular customer            10
57        1  Regular customer            10
58        1  Regular customer            10
59        1  Regular customer            11
60        2  Regular customer             1
61        2  Regular customer             1
62        2  Regular customer             1
63        2  Regular customer             1
64        2  Regular customer             1
65        2  Regular customer             1
66        2  Regular customer             1
67        2  Regular customer             1
68        2  Regular customer             1
69        2  Regular customer             1
70        2  Regular customer             1
71        2  Regular customer             1
72        2  Regular customer             1
73        2  Regular customer             2
74        2  Regular customer             2
75        2  Regular customer             2
76        2  Regular customer             2
77        2  Regular customer             2
78        2  Regular customer             2
79        2  Regular customer             3
80        2  Regular customer             3
81        2  Regular customer             3
82        2  Regular customer             3
83        2  Regular customer             3
84        2  Regular customer             4
85        2  Regular customer             4
86        2  Regular customer             4
87        2  Regular customer             4
88        2  Regular customer             4
89        2  Regular customer             4
90        2  Regular customer             4
91        2  Regular customer             4
92        2  Regular customer             4
93        2  Regular customer             4
94        2  Regular customer             4
95        2  Regular customer             4
96        2  Regular customer             4
97        2  Regular customer             5
98        2  Regular customer             5
99        2  Regular customer             5

__TASK 4.8__

#2. In this Exercise, you learned how to find the aggregated mean of the “order_number” column grouped by “department_id” for a subset of your dataframe. Now, repeat this process for the entire dataframe.

In [24]:
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              15.457838
2.0              17.277920
3.0              17.170395
4.0              17.811403
5.0              15.215751
6.0              16.439806
7.0              17.225802
8.0              15.340650
9.0              15.895474
10.0             20.197148
11.0             16.170638
12.0             15.887671
13.0             16.583536
14.0             16.773669
15.0             16.165037
16.0             17.665606
17.0             15.694469
18.0             19.310397
19.0             17.177343
20.0             16.473447
21.0             22.902379

#3 Analyze the result. How do the results for the entire dataframe differ from those of the subset? Include your comments in a markdown cell below the executed code.

In [25]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1.0              14.794925
2.0              17.085793
3.0              17.892742
4.0              17.880137
5.0              15.108513
6.0              15.352869
7.0              17.682741
8.0              16.496386
9.0              15.944846
10.0             20.104831
11.0             16.483104
12.0             15.614125
13.0             16.458631
14.0             17.523399
15.0             15.673392
16.0             18.012021
17.0             15.842139
18.0             19.349156
19.0             17.625805
20.0             17.113240
21.0             22.009038

#answer 3. the result is slightly difference from the entire data set(which is understanable since we are comparing only a subset of the data), however the mean are showing similar pattern with the entire data set.

#4. Follow the instructions in the Exercise for creating a loyalty flag for existing customers using the transform() and loc() functions.

- this has been done on the example above-

#5.The marketing team at Instacart wants to know whether there’s a difference between the spending habits of the three types of customers you identified. Use the loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer). What you’re trying to determine is whether the prices of products purchased by loyal customers differ from those purchased by regular or new customers.

In [26]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices': ['mean', 'min', 'max']})

                     prices
                       mean  min      max
loyalty_flag
Loyal customer    10.377144  1.0  99999.0
New customer      13.208437  1.0  99999.0
Regular customer  12.616225  1.0  99999.0

#loyal customer tends to spend on average 10 USD,new customer 13 USD and regular customer spends on average 12 USD
this seem to be quite reasonable - we needs perhaps to also compare the order frequency from each group of customer.

#6 The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at 
the prices of the items people are buying. 

Create a spending flag for each user based on the average price across all their 
orders using the following criteria:

1.If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”

2.If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [27]:
ords_prods_merge.groupby('user_id').agg({'prices': ['mean', 'min', 'max']}).head(5)

           prices
             mean  min   max
user_id
1        6.367797  1.0  14.0
2        7.515897  1.3  14.8
3        8.197727  1.3  14.4
4        8.205556  1.4  14.6
5        9.189189  3.2  14.8

#this command works - we have in total __206.208__ user !!!

#6.The team now wants to target different types of spenders in their marketing campaigns. This can be achieved by looking at the prices of the items people are buying. Create a spending flag for each user based on the average price across all their orders using the following criteria:
If the mean of the prices of products purchased by a user is lower than 10, then flag them as a “Low spender.”
If the mean of the prices of products purchased by a user is higher than or equal to 10, then flag them as a “High spender.”

In [28]:
ords_prods_merge['spending'] = ords_prods_merge.groupby(['user_id'])['prices'].transform(np.mean)

In [29]:
ords_prods_merge.loc[ords_prods_merge['spending'] < 10, 'spending_flag'] = 'Low Spender'
ords_prods_merge.loc[ords_prods_merge['spending'] >= 10, 'spending_flag'] = 'High Spender'

In [30]:
ords_prods_merge.head(5)

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,first_order,product_id,add_to_cart_order,reordered,...,prices,_merge,price_range_loc,busiest_day,busiest_days,busiest_period_of_day,max_order,loyalty_flag,spending,spending_flag
0,2539329,1,1,2,8,NaN,True,196.0,1.0,0.0,...,9.0,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,11,Regular customer,6.367797,Low Spender
1,2539329,1,1,2,8,NaN,True,14084.0,2.0,0.0,...,12.5,both,Mid-range product,Regularly busy,Regularly busy days,Average orders,11,Regular customer,6.367797,Low Spender
2,2539329,1,1,2,8,NaN,True,12427.0,3.0,0.0,...,4.4,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11,Regular customer,6.367797,Low Spender
3,2539329,1,1,2,8,NaN,True,26088.0,4.0,0.0,...,4.7,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11,Regular customer,6.367797,Low Spender
4,2539329,1,1,2,8,NaN,True,26405.0,5.0,0.0,...,1.0,both,Low-range product,Regularly busy,Regularly busy days,Average orders,11,Regular customer,6.367797,Low Spender

In [31]:
ords_prods_merge['spending_flag'].value_counts(dropna = False)

Low Spender     32001268
High Spender      640000
Name: spending_flag, dtype: int64

In [34]:
ords_prods_merge.groupby('user_id')['spending_flag']

#7. In order to send relevant notifications to users within the app (for instance, asking users if they want to buy the same item again), the Instacart team wants you to determine frequent versus non-frequent customers. Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column. The criteria for the flag should be as follows:
If the median of “days_since_prior_order” is higher than 20, then the customer should be labeled a “Non-frequent customer.”
If the median is higher than 10 and lower than or equal to 20, then the customer should be labeled a “Regular customer.”
If the median is lower than or equal to 10, then the customer should be labeled a “Frequent customer.”

In [35]:
ords_prods_merge['frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.median)

In [40]:
ords_prods_merge.loc[ords_prods_merge['frequency'] > 20, 'frequency_flag'] = 'Non-frequent customer'

In [43]:
ords_prods_merge.loc[(ords_prods_merge['frequency'] <= 20) & (ords_prods_merge['frequency'] > 10), 'frequency_flag'] = 'Regular customer'

In [44]:
ords_prods_merge.loc[ords_prods_merge['frequency'] <= 10, 'frequency_flag'] = 'Frequent customer'

In [45]:
ords_prods_merge['frequency_flag'].value_counts(dropna = False)

Frequent customer        21639188
Regular customer          7287469
Non-frequent customer     3714611
Name: frequency_flag, dtype: int64

In [47]:
ords_prods_merge[['user_id', 'frequency', 'frequency_flag']].head(200)

     user_id  frequency    frequency_flag
0          1       20.0  Regular customer
1          1       20.0  Regular customer
2          1       20.0  Regular customer
3          1       20.0  Regular customer
4          1       20.0  Regular customer
5          1       20.0  Regular customer
6          1       20.0  Regular customer
7          1       20.0  Regular customer
8          1       20.0  Regular customer
9          1       20.0  Regular customer
10         1       20.0  Regular customer
11         1       20.0  Regular customer
12         1       20.0  Regular customer
13         1       20.0  Regular customer
14         1       20.0  Regular customer
15         1       20.0  Regular customer
16         1       20.0  Regular customer
17         1       20.0  Regular customer
18         1       20.0  Regular customer
19         1       20.0  Regular customer
20         1       20.0  Regular customer
21         1       20.0  Regular customer
22         1       20.0  Regular customer
23         1       20.0  Regular customer
24         1       20.0  Regular customer
25         1       20.0  Regular customer
26         1       20.0  Regular customer
27         1       20.0  Regular customer
28         1       20.0  Regular customer
29         1       20.0  Regular customer
30         1       20.0  Regular customer
31         1       20.0  Regular customer
32         1       20.0  Regular customer
33         1       20.0  Regular customer
34         1       20.0  Regular customer
35         1       20.0  Regular customer
36         1       20.0  Regular customer
37         1       20.0  Regular customer
38         1       20.0  Regular customer
39         1       20.0  Regular customer
40         1       20.0  Regular customer
41         1       20.0  Regular customer
42         1       20.0  Regular customer
43         1       20.0  Regular customer
44         1       20.0  Regular customer
45         1       20.0  Regular customer
46         1       20.0  Regular customer
47         1       20.0  Regular customer
48         1       20.0  Regular customer
49         1       20.0  Regular customer
50         1       20.0  Regular customer
51         1       20.0  Regular customer
52         1       20.0  Regular customer
53         1       20.0  Regular customer
54         1       20.0  Regular customer
55         1       20.0  Regular customer
56         1       20.0  Regular customer
57         1       20.0  Regular customer
58         1       20.0  Regular customer
59         1       20.0  Regular customer
60         2       13.0  Regular customer
61         2       13.0  Regular customer
62         2       13.0  Regular customer
63         2       13.0  Regular customer
64         2       13.0  Regular customer
65         2       13.0  Regular customer
66         2       13.0  Regular customer
67         2       13.0  Regular customer
68         2       13.0  Regular customer
69         2       13.0  Regular customer
70         2       13.0  Regular customer
71         2       13.0  Regular customer
72         2       13.0  Regular customer
73         2       13.0  Regular customer
74         2       13.0  Regular customer
75         2       13.0  Regular customer
76         2       13.0  Regular customer
77         2       13.0  Regular customer
78         2       13.0  Regular customer
79         2       13.0  Regular customer
80         2       13.0  Regular customer
81         2       13.0  Regular customer
82         2       13.0  Regular customer
83         2       13.0  Regular customer
84         2       13.0  Regular customer
85         2       13.0  Regular customer
86         2       13.0  Regular customer
87         2       13.0  Regular customer
88         2       13.0  Regular customer
89         2       13.0  Regular customer
90         2       13.0  Regular customer
91         2       13.0  Regular customer
92         2       13.0  Regular customer
93         2       13.0  Regular customer
94         2       13.0  Regular customer
95         2       13.0  Regular customer
96         2       13.0  Regular customer
97         2       13.0  Regular customer
98         2       13.0  Regular customer
99         2       13.0  Regular customer
100        2       13.0  Regular customer
101        2       13.0  Regular customer
102        2       13.0  Regular customer
103        2       13.0  Regular customer
104        2       13.0  Regular customer
105        2       13.0  Regular customer
106        2       13.0  Regular customer
107        2       13.0  Regular customer
108        2       13.0  Regular customer
109        2       13.0  Regular customer
110        2       13.0  Regular customer
111        2       13.0  Regular customer
112        2       13.0  Regular customer
113        2       13.0  Regular customer
114        2       13.0  Regular customer
115        2       13.0  Regular customer
116        2       13.0  Regular customer
117        2       13.0  Regular customer
118        2       13.0  Regular customer
119        2       13.0  Regular customer
120        2       13.0  Regular customer
121        2       13.0  Regular customer
122        2       13.0  Regular customer
123        2       13.0  Regular customer
124        2       13.0  Regular customer
125        2       13.0  Regular customer
126        2       13.0  Regular customer
127        2       13.0  Regular customer
128        2       13.0  Regular customer
129        2       13.0  Regular customer
130        2       13.0  Regular customer
131        2       13.0  Regular customer
132        2       13.0  Regular customer
133        2       13.0  Regular customer
134        2       13.0  Regular customer
135        2       13.0  Regular customer
136        2       13.0  Regular customer
137        2       13.0  Regular customer
138        2       13.0  Regular customer
139        2       13.0  Regular customer
140        2       13.0  Regular customer
141        2       13.0  Regular customer
142        2       13.0  Regular customer
143        2       13.0  Regular customer
144        2       13.0  Regular customer
145        2       13.0  Regular customer
146        2       13.0  Regular customer
147        2       13.0  Regular customer
148        2       13.0  Regular customer
149        2       13.0  Regular customer
150        2       13.0  Regular customer
151        2       13.0  Regular customer
152        2       13.0  Regular customer
153        2       13.0  Regular customer
154        2       13.0  Regular customer
155        2       13.0  Regular customer
156        2       13.0  Regular customer
157        2       13.0  Regular customer
158        2       13.0  Regular customer
159        2       13.0  Regular customer
160        2       13.0  Regular customer
161        2       13.0  Regular customer
162        2       13.0  Regular customer
163        2       13.0  Regular customer
164        2       13.0  Regular customer
165        2       13.0  Regular customer
166        2       13.0  Regular customer
167        2       13.0  Regular customer
168        2       13.0  Regular customer
169        2       13.0  Regular customer
170        2       13.0  Regular customer
171        2       13.0  Regular customer
172        2       13.0  Regular customer
173        2       13.0  Regular customer
174        2       13.0  Regular customer
175        2       13.0  Regular customer
176        2       13.0  Regular customer
177        2       13.0  Regular customer
178        2       13.0  Regular customer
179        2       13.0  Regular customer
180        2       13.0  Regular customer
181        2       13.0  Regular customer
182        2       13.0  Regular customer
183        2       13.0  Regular customer
184        2       13.0  Regular customer
185        2       13.0  Regular customer
186        2       13.0  Regular customer
187        2       13.0  Regular customer
188        2       13.0  Regular customer
189        2       13.0  Regular customer
190        2       13.0  Regular customer
191        2       13.0  Regular customer
192        2       13.0  Regular customer
193        2       13.0  Regular customer
194        2       13.0  Regular customer
195        2       13.0  Regular customer
196        2       13.0  Regular customer
197        2       13.0  Regular customer
198        2       13.0  Regular customer
199        2       13.0  Regular customer

In [54]:
ords_prods_merge.to_pickle(r'/Users/rayruslijunior/11-2021 Instacart Basket Analysis/02 Data/Prepared Data/4.8 orders_products_merged.pkl')